name: Shing Lyu
email: shing.lyu@gmail.com
highlighter: rouge 
markdown: kramdown
exclude_pages: ["Hi! I'm Shing Lyu", "JCMG Corpus", "RSS", "Blog"]
description: Shing Lyu's Portfolio and Blog
url: https://shinglyu.github.io
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      css: "/css/post.css"
      layout: post
